name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - "master"
      - "development"
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setting environment
        id: tag
        run: |
          if [[ $BRANCH == 'master' ]]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          else
            echo "TAG=$BRANCH" >> $GITHUB_OUTPUT
          fi
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}

  build-composer:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: composer:2.7.2
      volumes:
        - ./vendor:/app/vendor:z
        - ./composer.json:/app/composer.json:r
    steps:
      - name: Show folder structure
        run: ls -la
      - name: Run composer
        run: composer install --working-dir=/app --ignore-platform-reqs

  build:
    needs: build-composer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file ./docker/php/Dockerfile --tag test:{{ needs.setup.outputs.tag }}

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/faimmedia/php-migration/test:{{ needs.setup.outputs.tag }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    services:
      postgres:
        image: postgres:16-alpine3.19
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Run tests
        run: /app/bin/test
